/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicStreamRouteImport } from './routes/api/public/stream'
import { Route as WatchBatchIdSubjectIdTopicIdLectureIdRouteImport } from './routes/watch.$batchId.$subjectId.$topicId.$lectureId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStreamRoute = ApiPublicStreamRouteImport.update({
  id: '/api/public/stream',
  path: '/api/public/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchBatchIdSubjectIdTopicIdLectureIdRoute =
  WatchBatchIdSubjectIdTopicIdLectureIdRouteImport.update({
    id: '/watch/$batchId/$subjectId/$topicId/$lectureId',
    path: '/watch/$batchId/$subjectId/$topicId/$lectureId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
  '/watch/$batchId/$subjectId/$topicId/$lectureId': typeof WatchBatchIdSubjectIdTopicIdLectureIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
  '/watch/$batchId/$subjectId/$topicId/$lectureId': typeof WatchBatchIdSubjectIdTopicIdLectureIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
  '/watch/$batchId/$subjectId/$topicId/$lectureId': typeof WatchBatchIdSubjectIdTopicIdLectureIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/stream'
    | '/watch/$batchId/$subjectId/$topicId/$lectureId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/stream'
    | '/watch/$batchId/$subjectId/$topicId/$lectureId'
  id:
    | '__root__'
    | '/'
    | '/api/public/stream'
    | '/watch/$batchId/$subjectId/$topicId/$lectureId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicStreamRoute: typeof ApiPublicStreamRoute
  WatchBatchIdSubjectIdTopicIdLectureIdRoute: typeof WatchBatchIdSubjectIdTopicIdLectureIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stream': {
      id: '/api/public/stream'
      path: '/api/public/stream'
      fullPath: '/api/public/stream'
      preLoaderRoute: typeof ApiPublicStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$batchId/$subjectId/$topicId/$lectureId': {
      id: '/watch/$batchId/$subjectId/$topicId/$lectureId'
      path: '/watch/$batchId/$subjectId/$topicId/$lectureId'
      fullPath: '/watch/$batchId/$subjectId/$topicId/$lectureId'
      preLoaderRoute: typeof WatchBatchIdSubjectIdTopicIdLectureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicStreamRoute: ApiPublicStreamRoute,
  WatchBatchIdSubjectIdTopicIdLectureIdRoute:
    WatchBatchIdSubjectIdTopicIdLectureIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
